export const LABELS ={
    TITLE : 'CONNECT FOUR!',
    SUB_TITLE : 'Play with other players around the world.',
    TRADEMARK : '2020',
    PLAY : 'PLAY',
    COMING_SOON : 'Coming Soon',
    TWO_PLAYER_GAME : 'Two Players Game',
    PLAYER01 : 'Player 01',
    PLAYER02 : 'Player 02',
    NUMBER_OF_GAMES : 'Number of games',
    WHO_STARTS : 'Who Starts',
    START_GAME : 'Start Game',
    GAMES_TOURNAMENT : 'Games Tournament',
    PLAYING_GAME : 'Playing Game',
    SCORE : 'Score',
    UNDO_STEP : 'Undo Step',
    END_TOURNAMENT : 'End Tournament',
    NEXT_GAME : 'Next Game',
    CONGRATULATIONS : 'Congratulations',
    PLAYER01NAME : 'First Player Name',
    PLAYER02NAME : 'Second Player Name',
}